version: 2.1
jobs:
  e2e:
    working_directory: ./android
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew

  gradle:
    working_directory: ./android
    docker:
      - image: 'cimg/openjdk:11.0'
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:    
          name: Run Gradle build command
          command: ./gradlew build
